server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://zidtech-devs.b.aivencloud.com:27664/defaultdb?sslmode=require
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD} # Replace with your local DB password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# ==========================================
# ZidTech Common Security Library Config
# ==========================================
app:
  security:
    jwt-secret: ${JWT_SECRET} # Replace with your local JWT secret
    issuer: shopping-cart-auth-service
    access-token-ttl: 15m
    refresh-token-ttl: 14d
    refresh-cookie-name: shopping_refresh
    secure-cookies: false # Set to false for local HTTP development!

# Global Logging & Observability Baseline
logging:
  level:
    org.springframework.security: DEBUG
    com.zidtech: DEBUG